<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <DebugType>embedded</DebugType>
    <UserSecretsId>2bc4ae5c-65fa-4a7e-acd7-ae781d7f4327</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\PuzzleInput.txt" LogicalName="PuzzleInput.txt" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AdventOfCode.SecretEntrance.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdventOfCode.Common\AdventOfCode.Common.csproj" />
  </ItemGroup>

</Project>
